import React from "react";
import "./Blog.css";

export default function Blog3() {
  return (
    <>
      <article class="blog-content">
        <h2>Service Area</h2>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vel
          dolor ut velit ultricies tincidunt a sit amet neque. Nullam in
          suscipit nulla, eget elementum quam. In lacinia turpis ut ligula
          aliquam, nec luctus nisl scelerisque. Duis nec tellus at arcu blandit
          venenatis. Aenean scelerisque turpis ac erat aliquet, in aliquam urna
          laoreet. Fusce a ipsum vehicula, euismod justo in, aliquam turpis.
        </p>
        <h3>1. Urban Areas</h3>
        <p>
          We provide comprehensive waste management services in urban areas,
          ensuring timely collection and efficient processing of waste.
        </p>
        <h3>2. Suburban Areas</h3>
        <p>
          Our services extend to suburban regions, offering reliable waste
          management solutions to residents and businesses alike.
        </p>
        <h3>3. Rural Areas</h3>
        <p>
          We are committed to serving rural communities, providing sustainable
          waste management practices and promoting environmental awareness.
        </p>
        <h3>4. Industrial Zones</h3>
        <p>
          In industrial zones, we focus on managing hazardous and non-hazardous
          waste generated by various industries, ensuring compliance with
          environmental regulations.
        </p>
      </article>
    </>
  );
}
